# Generated by Django 6.0 on 2025-12-25 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del producto')),
                ('caracteristicas', models.TextField(verbose_name='Características')),
                ('precio_cop', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio (COP)')),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (USD)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='companies.empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
